### PR TITLE
Update gateway sample readme with additional information

### PR DESCRIPTION
**Pull request by denyeart**
Clean up instructions for v2.4.0-beta.
Add a description of the scenarios demonstrated in the sample client applications.
Minor cleanups to the scenario fixtures.

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

### CODE REVIEW

**Review by davidkel — COMMENTED** [review]
There is also an hsm-samples/README.md file which also references 2.4.0-alpha don't know if you want to include that in this PR as well ?

**Comment by jt-nti** [comment]
It would also be good to update [the doc](https://hyperledger.github.io/fabric-gateway/) from Tech Preview to Beta, with what's new etc. E.g. it still says "Currently the Gateway component in the Fabric Peer is disabled by default" which has been switched round I think.

**Comment by bestbeforetoday** [comment]
> It would also be good to update [the doc](https://hyperledger.github.io/fabric-gateway/) from Tech Preview to Beta, with what's new etc.

That would definitely be good. It may be worth noting that limited (experimental) chaincode event listening capability is included, which does not yet support event replay.

**Review by bestbeforetoday — APPROVED** [review]
These changes all look good to me. Additional comments can be addressed in a follow-up PR.

**Pull request merged**
